name: fake_store
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_neumorphic: ^3.2.0
  get: ^4.6.5
  google_fonts: ^4.0.1
  http: ^0.13.5
  shared_preferences:
  iconsax: ^0.0.8
  liquid_pull_to_refresh: ^3.0.1
  share_plus: ^6.3.0
  flutter_staggered_grid_view: ^0.6.2
  fluttertoast: ^8.2.1
  cloud_firestore: ^4.4.5
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  firebase_messaging: ^14.3.0
  firebase_core_web:
  firebase_core_platform_interface:
  firebase_database:

  geolocator:
  geocoding:



dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
